name: CI

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  ci:
    name: Build & Lint

    runs-on: ubuntu-latest

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.patrickgallagher.dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --ignore-scripts --no-progress
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Perform Sharp post-install scripts
        run: npm rebuild sharp

      - name: yarn build
        run: yarn build

      - name: yarn lint
        run: yarn lint
